[package]
name = "stm32h7-eth-example"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
panic-halt="0.2.0"
cortex-m = "0.7.4"
cortex-m-rt = "0.7.1"
cortex-m-rtic = "1.1"
stm32h7xx-hal = {version = "0.14.0", features = ["stm32h750v","rt", "ethernet", "smoltcp"]}

[dependencies.smoltcp]
version = "0.8.0"
default-features = false
features = ["medium-ethernet", "proto-ipv4", "socket-raw", "medium-ip", "socket-tcp", "socket-udp"]

[profile.release]
debug = 2
lto = true